"""transfer table

Revision ID: 53229f074438
Revises: c5f9b9f97002
Create Date: 2023-03-18 21:20:13.973123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53229f074438'
down_revision = 'c5f9b9f97002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_account', sa.Integer(), nullable=True),
    sa.Column('target_account', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=16), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Float(precision=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['currency'], ['account.currency'], ),
    sa.ForeignKeyConstraint(['source_account'], ['account.id'], ),
    sa.ForeignKeyConstraint(['target_account'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transfer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transfer_amount'), ['amount'], unique=False)
        batch_op.create_index(batch_op.f('ix_transfer_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transfer_date'), ['date'], unique=False)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'account', ['currency'], ['currency'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=True)

    with op.batch_alter_table('transfer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transfer_date'))
        batch_op.drop_index(batch_op.f('ix_transfer_created_at'))
        batch_op.drop_index(batch_op.f('ix_transfer_amount'))

    op.drop_table('transfer')
    # ### end Alembic commands ###
