"""category table

Revision ID: c5f9b9f97002
Revises: ebec8d4e9ad6
Create Date: 2023-03-17 11:47:37.377051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5f9b9f97002'
down_revision = 'ebec8d4e9ad6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('competence', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.Column('budget', sa.Float(precision=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('budget_archive', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_category_last_modified'), ['last_modified'], unique=False)

    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account', sa.Integer(), nullable=True),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(precision=64), nullable=True),
    sa.Column('currency', sa.String(length=16), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('tag', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['account'], ['account.id'], ),
    sa.ForeignKeyConstraint(['category'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_amount'), ['amount'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_date'), ['date'], unique=False)

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance_archive', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('balance_archive')

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_date'))
        batch_op.drop_index(batch_op.f('ix_transaction_created_at'))
        batch_op.drop_index(batch_op.f('ix_transaction_amount'))

    op.drop_table('transaction')
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_last_modified'))
        batch_op.drop_index(batch_op.f('ix_category_created_at'))

    op.drop_table('category')
    # ### end Alembic commands ###
